[package]
name = "bsan"
version = "0.1.0"
edition = "2021"

[dependencies]
env_logger = "0.11.5"
log = "0.4.22"
miri = { path = "../" }

[lib]
name = "borrowtracker"
crate-type = ["cdylib"] 

[build-dependencies]
cbindgen = "0.27.0"
